import json

# with open('dummyData.json', 'r') as f:
#     data = json.load(f)
# print(data["carts"])
#  print(data)
# for items in data["carts"]:
#     print(items["id"])


with open("dummyData.json" , "r") as f:
    item = json.load(f)
print(item)


users = [
    {
        "id": 1,
        "firstName": "Terry",
        "lastName": "Medhurst",
        "maidenName": "Smitham",
        "age": 50,
        "gender": "male",
        "email": "atuny0@sohu.com",
        "phone": "+63 791 675 8914",
        "username": "atuny0",
        "password": "9uQFF1Lh",
        "birthDate": "2000-12-25",
        "image": "https://robohash.org/hicveldicta.png",
        "bloodGroup": "A−",
        "height": 189,
        "weight": 75.4,
        "eyeColor": "Green",
        "hair": {"color": "Black", "type": "Strands"},
        "domain": "slashdot.org",
        "ip": "117.29.86.254",
        "address": {
            "address": "1745 T Street Southeast",
            "city": "Washington",
            "coordinates": {"lat": 38.867033, "lng": -76.979235},
            "postalCode": "20020",
            "state": "DC",
        },
        "macAddress": "13:69:BA:56:A3:74",
        "university": "Capitol University",
        "bank": {
            "cardExpire": "06/22",
            "cardNumber": "50380955204220685",
            "cardType": "maestro",
            "currency": "Peso",
            "iban": "NO17 0695 2754 967",
        },
        "company": {
            "address": {
                "address": "629 Debbie Drive",
                "city": "Nashville",
                "coordinates": {"lat": 36.208114, "lng": -86.58621199999999},
                "postalCode": "37076",
                "state": "TN",
            },
            "department": "Marketing",
            "name": "Blanda-O'Keefe",
            "title": "Help Desk Operator",
        },
        "ein": "20-9487066",
        "ssn": "661-64-2976",
        "userAgent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/12.0.702.0 Safari/534.24",
    },
    {
        "id": 2,
        "firstName": "Sheldon",
        "lastName": "Quigley",
        "maidenName": "Cole",
        "age": 28,
        "gender": "male",
        "email": "hbingley1@plala.or.jp",
        "phone": "+7 813 117 7139",
        "username": "hbingley1",
        "password": "CQutx25i8r",
        "birthDate": "2003-08-02",
        "image": "https://robohash.org/doloremquesintcorrupti.png",
        "bloodGroup": "O+",
        "height": 187,
        "weight": 74,
        "eyeColor": "Brown",
        "hair": {"color": "Blond", "type": "Curly"},
        "domain": "51.la",
        "ip": "253.240.20.181",
        "address": {
            "address": "6007 Applegate Lane",
            "city": "Louisville",
            "coordinates": {"lat": 38.1343013, "lng": -85.6498512},
            "postalCode": "40219",
            "state": "KY",
        },
        "macAddress": "13:F1:00:DA:A4:12",
        "university": "Stavropol State Technical University",
        "bank": {
            "cardExpire": "10/23",
            "cardNumber": "5355920631952404",
            "cardType": "mastercard",
            "currency": "Ruble",
            "iban": "MD63 L6YC 8YH4 QVQB XHIK MTML",
        },
        "company": {
            "address": {
                "address": "8821 West Myrtle Avenue",
                "city": "Glendale",
                "coordinates": {"lat": 33.5404296, "lng": -112.2488391},
                "postalCode": "85305",
                "state": "AZ",
            },
            "department": "Services",
            "name": "Aufderhar-Cronin",
            "title": "Senior Cost Accountant",
        },
        "ein": "52-5262907",
        "ssn": "447-08-9217",
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/11.04 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30",
    },
    {
        "id": 3,
        "firstName": "Terrill",
        "lastName": "Hills",
        "maidenName": "Hoeger",
        "age": 38,
        "gender": "male",
        "email": "rshawe2@51.la",
        "phone": "+63 739 292 7942",
        "username": "rshawe2",
        "password": "OWsTbMUgFc",
        "birthDate": "1992-12-30",
        "image": "https://robohash.org/consequunturautconsequatur.png",
        "bloodGroup": "A−",
        "height": 200,
        "weight": 105.3,
        "eyeColor": "Gray",
        "hair": {"color": "Blond", "type": "Very curly"},
        "domain": "earthlink.net",
        "ip": "205.226.160.3",
        "address": {
            "address": "560 Penstock Drive",
            "city": "Grass Valley",
            "coordinates": {"lat": 39.213076, "lng": -121.077583},
            "postalCode": "95945",
            "state": "CA",
        },
        "macAddress": "F2:88:58:64:F7:76",
        "university": "University of Cagayan Valley",
        "bank": {
            "cardExpire": "10/23",
            "cardNumber": "3586082982526703",
            "cardType": "jcb",
            "currency": "Peso",
            "iban": "AT24 1095 9625 1434 9703",
        },
        "company": {
            "address": {
                "address": "18 Densmore Drive",
                "city": "Essex",
                "coordinates": {"lat": 44.492953, "lng": -73.101883},
                "postalCode": "05452",
                "state": "VT",
            },
            "department": "Marketing",
            "name": "Lindgren LLC",
            "title": "Mechanical Systems Engineer",
        },
        "ein": "48-3951994",
        "ssn": "633-89-1926",
        "userAgent": "Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:21.0.0) Gecko/20121011 Firefox/21.0.0",
    },
    {
        "id": 4,
        "firstName": "Miles",
        "lastName": "Cummerata",
        "maidenName": "Maggio",
        "age": 49,
        "gender": "male",
        "email": "yraigatt3@nature.com",
        "phone": "+86 461 145 4186",
        "username": "yraigatt3",
        "password": "sRQxjPfdS",
        "birthDate": "1969-01-16",
        "image": "https://robohash.org/facilisdignissimosdolore.png",
        "bloodGroup": "B+",
        "height": 157,
        "weight": 95.9,
        "eyeColor": "Gray",
        "hair": {"color": "Blond", "type": "Very curly"},
        "domain": "homestead.com",
        "ip": "243.20.78.113",
        "address": {
            "address": "150 Carter Street",
            "city": "Manchester",
            "coordinates": {"lat": 41.76556000000001, "lng": -72.473091},
            "postalCode": "06040",
            "state": "CT",
        },
        "macAddress": "03:45:58:59:5A:7B",
        "university": "Shenyang Pharmaceutical University",
        "bank": {
            "cardExpire": "07/24",
            "cardNumber": "3580047879369323",
            "cardType": "jcb",
            "currency": "Yuan Renminbi",
            "iban": "KZ43 658B M6VS TZOU OXSO",
        },
        "company": {
            "address": {
                "address": "210 Green Road",
                "city": "Manchester",
                "coordinates": {"lat": 41.7909099, "lng": -72.51195129999999},
                "postalCode": "06042",
                "state": "CT",
            },
            "department": "Business Development",
            "name": "Wolff and Sons",
            "title": "Paralegal",
        },
        "ein": "71-3644334",
        "ssn": "487-28-6642",
        "userAgent": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.17 Safari/537.11",
    },
    {
        "id": 5,
        "firstName": "Mavis",
        "lastName": "Schultz",
        "maidenName": "Yundt",
        "age": 38,
        "gender": "male",
        "email": "kmeus4@upenn.edu",
        "phone": "+372 285 771 1911",
        "username": "kmeus4",
        "password": "aUTdmmmbH",
        "birthDate": "1968-11-03",
        "image": "https://robohash.org/adverovelit.png",
        "bloodGroup": "O+",
        "height": 188,
        "weight": 106.3,
        "eyeColor": "Brown",
        "hair": {"color": "Brown", "type": "Curly"},
        "domain": "columbia.edu",
        "ip": "103.72.86.183",
        "address": {
            "address": "2721 Lindsay Avenue",
            "city": "Louisville",
            "coordinates": {"lat": 38.263793, "lng": -85.700243},
            "postalCode": "40206",
            "state": "KY",
        },
        "macAddress": "F8:04:9E:ED:C0:68",
        "university": "Estonian University of Life Sciences",
        "bank": {
            "cardExpire": "01/24",
            "cardNumber": "4917245076693618",
            "cardType": "visa-electron",
            "currency": "Euro",
            "iban": "IT41 T114 5127 716J RGYB ZRUX DSJ",
        },
        "company": {
            "address": {
                "address": "8398 West Denton Lane",
                "city": "Glendale",
                "coordinates": {"lat": 33.515353, "lng": -112.240812},
                "postalCode": "85305",
                "state": "AZ",
            },
            "department": "Support",
            "name": "Adams Inc",
            "title": "Web Developer I",
        },
        "ein": "18-7178563",
        "ssn": "667-98-5357",
        "userAgent": "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.1 Safari/535.1",
    },
]
# myUser = []
# for item in users:
#     temp = {
#         "myId" : item["id"],
#         "name" : item["firstName"] + item["lastName"],
#         "age" : item["age"],
#         "myGender" : item["gender"],
#         "phoneNo" : item["phone"]

#     }
#     myUser.append(temp)
# print(myUser)
# for x in myUser:
#     print(x)


products = [
    {
        "id": 1,
        "title": "iPhone 9",
        "description": "An apple mobile which is nothing like apple",
        "price": 549,
        "discountPercentage": 12.96,
        "rating": 4.69,
        "stock": 94,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/1/1.jpg",
            "https://i.dummyjson.com/data/products/1/2.jpg",
            "https://i.dummyjson.com/data/products/1/3.jpg",
            "https://i.dummyjson.com/data/products/1/4.jpg",
            "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
        ],
    },
    {
        "id": 2,
        "title": "iPhone X",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/2/1.jpg",
            "https://i.dummyjson.com/data/products/2/2.jpg",
            "https://i.dummyjson.com/data/products/2/3.jpg",
            "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
        ],
    },
    {
        "id": 3,
        "title": "Samsung Universe 9",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "discountPercentage": 15.46,
        "rating": 4.09,
        "stock": 36,
        "brand": "Samsung",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/3/1.jpg"],
    },
    {
        "id": 4,
        "title": "OPPOF19",
        "description": "OPPO F19 is officially announced on April 2021.",
        "price": 280,
        "discountPercentage": 17.91,
        "rating": 4.3,
        "stock": 123,
        "brand": "OPPO",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/4/1.jpg",
            "https://i.dummyjson.com/data/products/4/2.jpg",
            "https://i.dummyjson.com/data/products/4/3.jpg",
            "https://i.dummyjson.com/data/products/4/4.jpg",
            "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
        ],
    },
    {
        "id": 5,
        "title": "Huawei P30",
        "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "discountPercentage": 10.58,
        "rating": 4.09,
        "stock": 32,
        "brand": "Huawei",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
        "images": [
            "https://i.dummyjson.com/data/products/5/1.jpg",
            "https://i.dummyjson.com/data/products/5/2.jpg",
            "https://i.dummyjson.com/data/products/5/3.jpg",
        ],
    },
    {
        "id": 6,
        "title": "MacBook Pro",
        "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
        "price": 1749,
        "discountPercentage": 11.02,
        "rating": 4.57,
        "stock": 83,
        "brand": "Apple",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png",
        "images": [
            "https://i.dummyjson.com/data/products/6/1.png",
            "https://i.dummyjson.com/data/products/6/2.jpg",
            "https://i.dummyjson.com/data/products/6/3.png",
            "https://i.dummyjson.com/data/products/6/4.jpg",
        ],
    },
]


# myProduct = []
# for item in products:
#     # print(item)
#      temp = {
#            "myId" : item["id"],
#            "myTitle" : item["title"],
#            "cost" : item["price"],
#            "rating" : item["rating"],
#            "stock" : item["stock"],
#            "brand" : item["brand"],
#            "category" : item["category"],
#            "image" : item["images"],
#            }
#      myProduct.append(temp)
#  print(myProduct)
# for x in myProduct:
#      print(x)


posts = [
    {
        "id": 1,
        "title": "His mother had always taught him",
        "body": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
        "userId": 9,
        "tags": ["history", "american", "crime"],
        "reactions": 2,
    },
    {
        "id": 2,
        "title": "He was an expert but not in a discipline",
        "body": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
        "userId": 13,
        "tags": ["french", "fiction", "english"],
        "reactions": 2,
    },
    {
        "id": 3,
        "title": "Dave watched as the forest burned up on the hill.",
        "body": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to round up the last of the pets. Dave went through his mental list of the most important papers and documents that they couldn't leave behind. He scolded himself for not having prepared these better in advance and hoped that he had remembered everything that was needed. He continued to wait for Marta to appear with the pets, but she still was nowhere to be seen.",
        "userId": 32,
        "tags": ["magical", "history", "french"],
        "reactions": 5,
    },
    {
        "id": 4,
        "title": "All he wanted was a candy bar.",
        "body": "All he wanted was a candy bar. It didn't seem like a difficult request to comprehend, but the clerk remained frozen and didn't seem to want to honor the request. It might have had something to do with the gun pointed at his face.",
        "userId": 12,
        "tags": ["mystery", "english", "american"],
        "reactions": 1,
    },
    {
        "id": 5,
        "title": "Hopes and dreams were dashed that day.",
        "body": "Hopes and dreams were dashed that day. It should have been expected, but it still came as a shock. The warning signs had been ignored in favor of the possibility, however remote, that it could actually happen. That possibility had grown from hope to an undeniable belief it must be destiny. That was until it wasn't and the hopes and dreams came crashing down.",
        "userId": 41,
        "tags": ["crime", "mystery", "love"],
        "reactions": 2,
    },
]

# post = []
# for items in posts:
#     temp = {
#         "myId" : items["id"],
#         "myBody" : items["body"],
#         "ourUserId" : items["userId"],
#         "tag" : items["tags"],
#         "reaction" : items["reactions"]

#     }
#     post.append(temp)
# print(post)


quotes = [
    {
        "id": 1,
        "quote": "Life isn’t about getting and having, it’s about giving and being.",
        "author": "Kevin Kruse",
    },
    {
        "id": 2,
        "quote": "Whatever the mind of man can conceive and believe, it can achieve.",
        "author": "Napoleon Hill",
    },
    {
        "id": 3,
        "quote": "Strive not to be a success, but rather to be of value.",
        "author": "Albert Einstein",
    },
    {
        "id": 4,
        "quote": "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
        "author": "Robert Frost",
    },
    {
        "id": 5,
        "quote": "I attribute my success to this: I never gave or took any excuse.",
        "author": "Florence Nightingale",
    },
    {
        "id": 6,
        "quote": "You miss 100% of the shots you don’t take.",
        "author": "Wayne Gretzky",
    },
    {
        "id": 7,
        "quote": "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
        "author": "Michael Jordan",
    },
    {
        "id": 8,
        "quote": "The most difficult thing is the decision to act, the rest is merely tenacity.",
        "author": "Amelia Earhart",
    },
    {
        "id": 9,
        "quote": "Every strike brings me closer to the next home run.",
        "author": "Babe Ruth",
    },
    {
        "id": 10,
        "quote": "Definiteness of purpose is the starting point of all achievement.",
        "author": "W. Clement Stone",
    },
    {
        "id": 11,
        "quote": "We must balance conspicuous consumption with conscious capitalism.",
        "author": "Kevin Kruse",
    },
    {
        "id": 12,
        "quote": "Life is what happens to you while you’re busy making other plans.",
        "author": "John Lennon",
    },
    {"id": 13, "quote": "We become what we think about.", "author": "Earl Nightingale"},
    {
        "id": 14,
        "quote": "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.",
        "author": "Mark Twain",
    },
    {
        "id": 15,
        "quote": "Life is 10% what happens to me and 90% of how I react to it.",
        "author": "Charles Swindoll",
    },
    {
        "id": 16,
        "quote": "The most common way people give up their power is by thinking they don’t have any.",
        "author": "Alice Walker",
    },
]
# quote = []
# for data in quotes:

#     temp = {
#         "myId" : data["id"],
#         "line" : data["quote"],
#         "writer" : data["author"],
#         }
#     quote.append(temp)
# print(quote)
# for x in quote:
#     print(x)


carts = [
    {
        "id": 1,
        "products": [
            {
                "id": 59,
                "title": "Spring and summershoes",
                "price": 20,
                "quantity": 3,
                "total": 60,
                "discountPercentage": 8.71,
                "discountedPrice": 55,
            },
            {
                "id": 88,
                "title": "TC Reusable Silicone Magic Washing Gloves",
                "price": 29,
                "quantity": 2,
                "total": 58,
                "discountPercentage": 3.19,
                "discountedPrice": 56,
            },
            {
                "id": 18,
                "title": "Oil Free Moisturizer 100ml",
                "price": 40,
                "quantity": 2,
                "total": 80,
                "discountPercentage": 13.1,
                "discountedPrice": 70,
            },
            {
                "id": 95,
                "title": "Wholesale cargo lashing Belt",
                "price": 930,
                "quantity": 1,
                "total": 930,
                "discountPercentage": 17.67,
                "discountedPrice": 766,
            },
            {
                "id": 39,
                "title": "Women Sweaters Wool",
                "price": 600,
                "quantity": 2,
                "total": 1200,
                "discountPercentage": 17.2,
                "discountedPrice": 994,
            },
        ],
        "total": 2328,
        "discountedTotal": 1941,
        "userId": 97,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 2,
        "products": [
            {
                "id": 96,
                "title": "lighting ceiling kitchen",
                "price": 30,
                "quantity": 2,
                "total": 60,
                "discountPercentage": 14.89,
                "discountedPrice": 51,
            },
            {
                "id": 91,
                "title": "Black Motorbike",
                "price": 569,
                "quantity": 3,
                "total": 1707,
                "discountPercentage": 13.63,
                "discountedPrice": 1474,
            },
            {
                "id": 9,
                "title": "Infinix INBOOK",
                "price": 1099,
                "quantity": 1,
                "total": 1099,
                "discountPercentage": 11.83,
                "discountedPrice": 969,
            },
            {
                "id": 16,
                "title": "Hyaluronic Acid Serum",
                "price": 19,
                "quantity": 1,
                "total": 19,
                "discountPercentage": 13.31,
                "discountedPrice": 16,
            },
            {
                "id": 54,
                "title": "Pubg Printed Graphic T-Shirt",
                "price": 46,
                "quantity": 3,
                "total": 138,
                "discountPercentage": 16.44,
                "discountedPrice": 115,
            },
        ],
        "total": 3023,
        "discountedTotal": 2625,
        "userId": 30,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 3,
        "products": [
            {
                "id": 37,
                "title": "ank Tops for Womens/Girls",
                "price": 50,
                "quantity": 2,
                "total": 100,
                "discountPercentage": 12.05,
                "discountedPrice": 88,
            },
            {
                "id": 80,
                "title": "Chain Pin Tassel Earrings",
                "price": 45,
                "quantity": 3,
                "total": 135,
                "discountPercentage": 17.75,
                "discountedPrice": 111,
            },
            {
                "id": 68,
                "title": "Stylish Luxury Digital Watch",
                "price": 57,
                "quantity": 3,
                "total": 171,
                "discountPercentage": 9.03,
                "discountedPrice": 156,
            },
            {
                "id": 81,
                "title": "Round Silver Frame Sun Glasses",
                "price": 19,
                "quantity": 1,
                "total": 19,
                "discountPercentage": 10.1,
                "discountedPrice": 17,
            },
            {
                "id": 90,
                "title": "Cycle Bike Glow",
                "price": 35,
                "quantity": 1,
                "total": 35,
                "discountPercentage": 11.08,
                "discountedPrice": 31,
            },
        ],
        "total": 460,
        "discountedTotal": 403,
        "userId": 63,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 4,
        "products": [
            {
                "id": 36,
                "title": "Sleeve Shirt Womens",
                "price": 90,
                "quantity": 1,
                "total": 90,
                "discountPercentage": 10.89,
                "discountedPrice": 80,
            },
            {
                "id": 54,
                "title": "Pubg Printed Graphic T-Shirt",
                "price": 46,
                "quantity": 1,
                "total": 46,
                "discountPercentage": 16.44,
                "discountedPrice": 38,
            },
            {
                "id": 11,
                "title": "perfume Oil",
                "price": 13,
                "quantity": 3,
                "total": 39,
                "discountPercentage": 8.4,
                "discountedPrice": 36,
            },
            {
                "id": 47,
                "title": "Sneaker shoes",
                "price": 120,
                "quantity": 2,
                "total": 240,
                "discountPercentage": 10.37,
                "discountedPrice": 215,
            },
            {
                "id": 64,
                "title": "Leather Strap Skeleton Watch",
                "price": 46,
                "quantity": 3,
                "total": 138,
                "discountPercentage": 10.2,
                "discountedPrice": 124,
            },
        ],
        "total": 553,
        "discountedTotal": 493,
        "userId": 83,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 5,
        "products": [
            {
                "id": 23,
                "title": "Orange Essence Food Flavou",
                "price": 14,
                "quantity": 3,
                "total": 42,
                "discountPercentage": 8.04,
                "discountedPrice": 39,
            },
            {
                "id": 91,
                "title": "Black Motorbike",
                "price": 569,
                "quantity": 1,
                "total": 569,
                "discountPercentage": 13.63,
                "discountedPrice": 491,
            },
            {
                "id": 45,
                "title": "Malai Maxi Dress",
                "price": 50,
                "quantity": 2,
                "total": 100,
                "discountPercentage": 5.07,
                "discountedPrice": 95,
            },
            {
                "id": 84,
                "title": "Square Sunglasses",
                "price": 28,
                "quantity": 1,
                "total": 28,
                "discountPercentage": 13.89,
                "discountedPrice": 24,
            },
            {
                "id": 70,
                "title": "Stainless Steel Women",
                "price": 35,
                "quantity": 3,
                "total": 105,
                "discountPercentage": 8.98,
                "discountedPrice": 96,
            },
        ],
        "total": 844,
        "discountedTotal": 745,
        "userId": 58,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 6,
        "products": [
            {
                "id": 53,
                "title": "printed high quality T shirts",
                "price": 35,
                "quantity": 3,
                "total": 105,
                "discountPercentage": 7.54,
                "discountedPrice": 97,
            },
            {
                "id": 61,
                "title": "Leather Straps Wristwatch",
                "price": 120,
                "quantity": 2,
                "total": 240,
                "discountPercentage": 7.14,
                "discountedPrice": 223,
            },
            {
                "id": 92,
                "title": "HOT SALE IN EUROPE electric racing motorcycle",
                "price": 920,
                "quantity": 1,
                "total": 920,
                "discountPercentage": 14.4,
                "discountedPrice": 788,
            },
            {
                "id": 11,
                "title": "perfume Oil",
                "price": 13,
                "quantity": 3,
                "total": 39,
                "discountPercentage": 8.4,
                "discountedPrice": 36,
            },
            {
                "id": 37,
                "title": "ank Tops for Womens/Girls",
                "price": 50,
                "quantity": 3,
                "total": 150,
                "discountPercentage": 12.05,
                "discountedPrice": 132,
            },
        ],
        "total": 1454,
        "discountedTotal": 1276,
        "userId": 26,
        "totalProducts": 5,
        "totalQuantity": 12,
    },
    {
        "id": 7,
        "products": [
            {
                "id": 61,
                "title": "Leather Straps Wristwatch",
                "price": 120,
                "quantity": 1,
                "total": 120,
                "discountPercentage": 7.14,
                "discountedPrice": 111,
            },
            {
                "id": 80,
                "title": "Chain Pin Tassel Earrings",
                "price": 45,
                "quantity": 2,
                "total": 90,
                "discountPercentage": 17.75,
                "discountedPrice": 74,
            },
            {
                "id": 99,
                "title": "American Vintage Wood Pendant Light",
                "price": 46,
                "quantity": 3,
                "total": 138,
                "discountPercentage": 8.84,
                "discountedPrice": 126,
            },
            {
                "id": 14,
                "title": "Non-Alcoholic Concentrated Perfume Oil",
                "price": 120,
                "quantity": 1,
                "total": 120,
                "discountPercentage": 15.6,
                "discountedPrice": 101,
            },
            {
                "id": 48,
                "title": "Women Strip Heel",
                "price": 40,
                "quantity": 3,
                "total": 120,
                "discountPercentage": 10.83,
                "discountedPrice": 107,
            },
        ],
        "total": 588,
        "discountedTotal": 519,
        "userId": 56,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 8,
        "products": [
            {
                "id": 45,
                "title": "Malai Maxi Dress",
                "price": 50,
                "quantity": 1,
                "total": 50,
                "discountPercentage": 5.07,
                "discountedPrice": 47,
            },
            {
                "id": 83,
                "title": "Wiley X Night Vision Yellow Glasses",
                "price": 30,
                "quantity": 3,
                "total": 90,
                "discountPercentage": 6.33,
                "discountedPrice": 84,
            },
            {
                "id": 96,
                "title": "lighting ceiling kitchen",
                "price": 30,
                "quantity": 1,
                "total": 30,
                "discountPercentage": 14.89,
                "discountedPrice": 26,
            },
            {
                "id": 21,
                "title": "- Daal Masoor 500 grams",
                "price": 20,
                "quantity": 3,
                "total": 60,
                "discountPercentage": 4.81,
                "discountedPrice": 57,
            },
            {
                "id": 2,
                "title": "iphone X",
                "price": 899,
                "quantity": 1,
                "total": 899,
                "discountPercentage": 17.94,
                "discountedPrice": 738,
            },
        ],
        "total": 1129,
        "discountedTotal": 952,
        "userId": 1,
        "totalProducts": 5,
        "totalQuantity": 9,
    },
    {
        "id": 9,
        "products": [
            {
                "id": 74,
                "title": "Leather Hand Bag",
                "price": 57,
                "quantity": 3,
                "total": 171,
                "discountPercentage": 11.19,
                "discountedPrice": 152,
            },
            {
                "id": 10,
                "title": "HP Pavilion 15-DK1056WM",
                "price": 1099,
                "quantity": 3,
                "total": 3297,
                "discountPercentage": 6.18,
                "discountedPrice": 3093,
            },
            {
                "id": 19,
                "title": "Skin Beauty Serum.",
                "price": 46,
                "quantity": 2,
                "total": 92,
                "discountPercentage": 10.68,
                "discountedPrice": 82,
            },
            {
                "id": 53,
                "title": "printed high quality T shirts",
                "price": 35,
                "quantity": 1,
                "total": 35,
                "discountPercentage": 7.54,
                "discountedPrice": 32,
            },
            {
                "id": 13,
                "title": "Fog Scent Xpressio Perfume",
                "price": 13,
                "quantity": 1,
                "total": 13,
                "discountPercentage": 8.14,
                "discountedPrice": 12,
            },
        ],
        "total": 3608,
        "discountedTotal": 3371,
        "userId": 91,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 10,
        "products": [
            {
                "id": 75,
                "title": "Seven Pocket Women Bag",
                "price": 68,
                "quantity": 1,
                "total": 68,
                "discountPercentage": 14.87,
                "discountedPrice": 58,
            },
            {
                "id": 39,
                "title": "Women Sweaters Wool",
                "price": 600,
                "quantity": 1,
                "total": 600,
                "discountPercentage": 17.2,
                "discountedPrice": 497,
            },
            {
                "id": 3,
                "title": "Samsung Universe 9",
                "price": 1249,
                "quantity": 3,
                "total": 3747,
                "discountPercentage": 15.46,
                "discountedPrice": 3168,
            },
            {
                "id": 7,
                "title": "Samsung Galaxy Book",
                "price": 1499,
                "quantity": 1,
                "total": 1499,
                "discountPercentage": 4.15,
                "discountedPrice": 1437,
            },
            {
                "id": 93,
                "title": "Automatic Motor Gas Motorcycles",
                "price": 1050,
                "quantity": 3,
                "total": 3150,
                "discountPercentage": 3.34,
                "discountedPrice": 3045,
            },
        ],
        "total": 9064,
        "discountedTotal": 8205,
        "userId": 13,
        "totalProducts": 5,
        "totalQuantity": 9,
    },
    {
        "id": 11,
        "products": [
            {
                "id": 71,
                "title": "Women Shoulder Bags",
                "price": 46,
                "quantity": 3,
                "total": 138,
                "discountPercentage": 14.65,
                "discountedPrice": 118,
            },
            {
                "id": 25,
                "title": "Gulab Powder 50 Gram",
                "price": 70,
                "quantity": 2,
                "total": 140,
                "discountPercentage": 13.58,
                "discountedPrice": 121,
            },
            {
                "id": 65,
                "title": "Stainless Steel Wrist Watch",
                "price": 47,
                "quantity": 3,
                "total": 141,
                "discountPercentage": 17.79,
                "discountedPrice": 116,
            },
            {
                "id": 58,
                "title": "formal offices shoes",
                "price": 57,
                "quantity": 1,
                "total": 57,
                "discountPercentage": 12,
                "discountedPrice": 50,
            },
            {
                "id": 53,
                "title": "printed high quality T shirts",
                "price": 35,
                "quantity": 3,
                "total": 105,
                "discountPercentage": 7.54,
                "discountedPrice": 97,
            },
        ],
        "total": 581,
        "discountedTotal": 502,
        "userId": 66,
        "totalProducts": 5,
        "totalQuantity": 12,
    },
    {
        "id": 12,
        "products": [
            {
                "id": 32,
                "title": "Sofa for Coffe Cafe",
                "price": 50,
                "quantity": 2,
                "total": 100,
                "discountPercentage": 15.59,
                "discountedPrice": 84,
            },
            {
                "id": 41,
                "title": "NIGHT SUIT",
                "price": 55,
                "quantity": 3,
                "total": 165,
                "discountPercentage": 15.05,
                "discountedPrice": 140,
            },
            {
                "id": 69,
                "title": "Golden Watch Pearls Bracelet Watch",
                "price": 47,
                "quantity": 1,
                "total": 47,
                "discountPercentage": 17.55,
                "discountedPrice": 39,
            },
            {
                "id": 98,
                "title": "3 lights lndenpant kitchen islang",
                "price": 34,
                "quantity": 3,
                "total": 102,
                "discountPercentage": 5.92,
                "discountedPrice": 96,
            },
            {
                "id": 67,
                "title": "Fashion Magnetic Wrist Watch",
                "price": 60,
                "quantity": 2,
                "total": 120,
                "discountPercentage": 16.69,
                "discountedPrice": 100,
            },
        ],
        "total": 534,
        "discountedTotal": 459,
        "userId": 52,
        "totalProducts": 5,
        "totalQuantity": 11,
    },
    {
        "id": 13,
        "products": [
            {
                "id": 81,
                "title": "Round Silver Frame Sun Glasses",
                "price": 19,
                "quantity": 1,
                "total": 19,
                "discountPercentage": 10.1,
                "discountedPrice": 17,
            },
            {
                "id": 42,
                "title": "Stiched Kurta plus trouser",
                "price": 80,
                "quantity": 2,
                "total": 160,
                "discountPercentage": 15.37,
                "discountedPrice": 135,
            },
            {
                "id": 29,
                "title": "Handcraft Chinese style",
                "price": 60,
                "quantity": 3,
                "total": 180,
                "discountPercentage": 15.34,
                "discountedPrice": 152,
            },
            {
                "id": 64,
                "title": "Leather Strap Skeleton Watch",
                "price": 46,
                "quantity": 2,
                "total": 92,
                "discountPercentage": 10.2,
                "discountedPrice": 83,
            },
            {
                "id": 54,
                "title": "Pubg Printed Graphic T-Shirt",
                "price": 46,
                "quantity": 1,
                "total": 46,
                "discountPercentage": 16.44,
                "discountedPrice": 38,
            },
        ],
        "total": 497,
        "discountedTotal": 425,
        "userId": 79,
        "totalProducts": 5,
        "totalQuantity": 9,
    },
    {
        "id": 14,
        "products": [
            {
                "id": 64,
                "title": "Leather Strap Skeleton Watch",
                "price": 46,
                "quantity": 2,
                "total": 92,
                "discountPercentage": 10.2,
                "discountedPrice": 83,
            },
            {
                "id": 76,
                "title": "Silver Ring Set Women",
                "price": 70,
                "quantity": 2,
                "total": 140,
                "discountPercentage": 13.57,
                "discountedPrice": 121,
            },
            {
                "id": 30,
                "title": "Key Holder",
                "price": 30,
                "quantity": 2,
                "total": 60,
                "discountPercentage": 2.92,
                "discountedPrice": 58,
            },
            {
                "id": 88,
                "title": "TC Reusable Silicone Magic Washing Gloves",
                "price": 29,
                "quantity": 1,
                "total": 29,
                "discountPercentage": 3.19,
                "discountedPrice": 28,
            },
            {
                "id": 94,
                "title": "new arrivals Fashion motocross goggles",
                "price": 900,
                "quantity": 2,
                "total": 1800,
                "discountPercentage": 3.85,
                "discountedPrice": 1731,
            },
        ],
        "total": 2121,
        "discountedTotal": 2021,
        "userId": 76,
        "totalProducts": 5,
        "totalQuantity": 9,
    },
    {
        "id": 15,
        "products": [
            {
                "id": 4,
                "title": "OPPOF19",
                "price": 280,
                "quantity": 1,
                "total": 280,
                "discountPercentage": 17.91,
                "discountedPrice": 230,
            },
            {
                "id": 100,
                "title": "Crystal chandelier maria theresa for 12 light",
                "price": 47,
                "quantity": 3,
                "total": 141,
                "discountPercentage": 16,
                "discountedPrice": 118,
            },
            {
                "id": 1,
                "title": "iPhone 9",
                "price": 549,
                "quantity": 2,
                "total": 1098,
                "discountPercentage": 12.96,
                "discountedPrice": 956,
            },
            {
                "id": 48,
                "title": "Women Strip Heel",
                "price": 40,
                "quantity": 3,
                "total": 120,
                "discountPercentage": 10.83,
                "discountedPrice": 107,
            },
            {
                "id": 94,
                "title": "new arrivals Fashion motocross goggles",
                "price": 900,
                "quantity": 3,
                "total": 2700,
                "discountPercentage": 3.85,
                "discountedPrice": 2596,
            },
        ],
        "total": 4339,
        "discountedTotal": 4007,
        "userId": 47,
        "totalProducts": 5,
        "totalQuantity": 12,
    },
    {
        "id": 16,
        "products": [
            {
                "id": 3,
                "title": "Samsung Universe 9",
                "price": 1249,
                "quantity": 3,
                "total": 3747,
                "discountPercentage": 15.46,
                "discountedPrice": 3168,
            },
            {
                "id": 50,
                "title": "Women Shoes",
                "price": 36,
                "quantity": 3,
                "total": 108,
                "discountPercentage": 16.87,
                "discountedPrice": 90,
            },
            {
                "id": 67,
                "title": "Fashion Magnetic Wrist Watch",
                "price": 60,
                "quantity": 2,
                "total": 120,
                "discountPercentage": 16.69,
                "discountedPrice": 100,
            },
            {
                "id": 86,
                "title": "Bluetooth Aux",
                "price": 25,
                "quantity": 1,
                "total": 25,
                "discountPercentage": 10.56,
                "discountedPrice": 22,
            },
            {
                "id": 12,
                "title": "Brown Perfume",
                "price": 40,
                "quantity": 1,
                "total": 40,
                "discountPercentage": 15.66,
                "discountedPrice": 34,
            },
        ],
        "total": 4040,
        "discountedTotal": 3414,
        "userId": 15,
        "totalProducts": 5,
        "totalQuantity": 10,
    },
    {
        "id": 17,
        "products": [
            {
                "id": 12,
                "title": "Brown Perfume",
                "price": 40,
                "quantity": 3,
                "total": 120,
                "discountPercentage": 15.66,
                "discountedPrice": 101,
            },
            {
                "id": 25,
                "title": "Gulab Powder 50 Gram",
                "price": 70,
                "quantity": 1,
                "total": 70,
                "discountPercentage": 13.58,
                "discountedPrice": 60,
            },
            {
                "id": 24,
                "title": "cereals muesli fruit nuts",
                "price": 46,
                "quantity": 2,
                "total": 92,
                "discountPercentage": 16.8,
                "discountedPrice": 77,
            },
            {
                "id": 90,
                "title": "Cycle Bike Glow",
                "price": 35,
                "quantity": 1,
                "total": 35,
                "discountPercentage": 11.08,
                "discountedPrice": 31,
            },
            {
                "id": 97,
                "title": "Metal Ceramic Flower",
                "price": 35,
                "quantity": 1,
                "total": 35,
                "discountPercentage": 10.94,
                "discountedPrice": 31,
            },
        ],
        "total": 352,
        "discountedTotal": 300,
        "userId": 56,
        "totalProducts": 5,
        "totalQuantity": 8,
    },
    {
        "id": 18,
        "products": [
            {
                "id": 23,
                "title": "Orange Essence Food Flavou",
                "price": 14,
                "quantity": 2,
                "total": 28,
                "discountPercentage": 8.04,
                "discountedPrice": 26,
            },
            {
                "id": 25,
                "title": "Gulab Powder 50 Gram",
                "price": 70,
                "quantity": 2,
                "total": 140,
                "discountPercentage": 13.58,
                "discountedPrice": 121,
            },
            {
                "id": 9,
                "title": "Infinix INBOOK",
                "price": 1099,
                "quantity": 2,
                "total": 2198,
                "discountPercentage": 11.83,
                "discountedPrice": 1938,
            },
            {
                "id": 78,
                "title": "Rhinestone Korean Style Open Rings",
                "price": 30,
                "quantity": 2,
                "total": 60,
                "discountPercentage": 8.02,
                "discountedPrice": 55,
            },
            {
                "id": 63,
                "title": "Royal Blue Premium Watch",
                "price": 50,
                "quantity": 1,
                "total": 50,
                "discountPercentage": 2.56,
                "discountedPrice": 49,
            },
        ],
        "total": 2476,
        "discountedTotal": 2189,
        "userId": 42,
        "totalProducts": 5,
        "totalQuantity": 9,
    },
]

# myData = []
# for data in carts:
#     temp ={
#         "myId" : data["id"],
#         "product" : data["products"],
#         "totals" : data["total"],
#         "discount" : data["discountedTotal"],
#         "quantity" : data["totalQuantity"]
#     }

#     myData.append(temp)
# print(myData)
# for x in myData:
#     print(x)


posts = [
    {
        "id": 1,
        "title": "His mother had always taught him",
        "body": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
        "userId": 9,
        "tags": ["history", "american", "crime"],
        "reactions": 2,
    },
    {
        "id": 2,
        "title": "He was an expert but not in a discipline",
        "body": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
        "userId": 13,
        "tags": ["french", "fiction", "english"],
        "reactions": 2,
    },
    {
        "id": 3,
        "title": "Dave watched as the forest burned up on the hill.",
        "body": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to round up the last of the pets. Dave went through his mental list of the most important papers and documents that they couldn't leave behind. He scolded himself for not having prepared these better in advance and hoped that he had remembered everything that was needed. He continued to wait for Marta to appear with the pets, but she still was nowhere to be seen.",
        "userId": 32,
        "tags": ["magical", "history", "french"],
        "reactions": 5,
    },
    {
        "id": 4,
        "title": "All he wanted was a candy bar.",
        "body": "All he wanted was a candy bar. It didn't seem like a difficult request to comprehend, but the clerk remained frozen and didn't seem to want to honor the request. It might have had something to do with the gun pointed at his face.",
        "userId": 12,
        "tags": ["mystery", "english", "american"],
        "reactions": 1,
    },
    {
        "id": 5,
        "title": "Hopes and dreams were dashed that day.",
        "body": "Hopes and dreams were dashed that day. It should have been expected, but it still came as a shock. The warning signs had been ignored in favor of the possibility, however remote, that it could actually happen. That possibility had grown from hope to an undeniable belief it must be destiny. That was until it wasn't and the hopes and dreams came crashing down.",
        "userId": 41,
        "tags": ["crime", "mystery", "love"],
        "reactions": 2,
    },
    {
        "id": 6,
        "title": "Dave wasn't exactly sure how he had ended up",
        "body": "Dave wasn't exactly sure how he had ended up in this predicament. He ran through all the events that had lead to this current situation and it still didn't make sense. He wanted to spend some time to try and make sense of it all, but he had higher priorities at the moment. The first was how to get out of his current situation of being naked in a tree with snow falling all around and no way for him to get down.",
        "userId": 47,
        "tags": ["english", "classic", "american"],
        "reactions": 3,
    },
    {
        "id": 7,
        "title": "This is important to remember.",
        "body": "This is important to remember. Love isn't like pie. You don't need to divide it among all your friends and loved ones. No matter how much love you give, you can always give more. It doesn't run out, so don't try to hold back giving it as if it may one day run out. Give it freely and as much as you want.",
        "userId": 12,
        "tags": ["magical", "crime"],
        "reactions": 0,
    },
    {
        "id": 8,
        "title": "One can cook on and with an open fire.",
        "body": "One can cook on and with an open fire. These are some of the ways to cook with fire outside. Cooking meat using a spit is a great way to evenly cook meat. In order to keep meat from burning, it's best to slowly rotate it.",
        "userId": 31,
        "tags": ["american", "english"],
        "reactions": 9,
    },
    {
        "id": 9,
        "title": "There are different types of secrets.",
        "body": "There are different types of secrets. She had held onto plenty of them during her life, but this one was different. She found herself holding onto the worst type. It was the type of secret that could gnaw away at your insides if you didn't tell someone about it, but it could end up getting you killed if you did.",
        "userId": 42,
        "tags": ["american", "history", "magical"],
        "reactions": 2,
    },
    {
        "id": 10,
        "title": "They rushed out the door.",
        "body": "They rushed out the door, grabbing anything and everything they could think of they might need. There was no time to double-check to make sure they weren't leaving something important behind. Everything was thrown into the car and they sped off. Thirty minutes later they were safe and that was when it dawned on them that they had forgotten the most important thing of all.",
        "userId": 1,
        "tags": ["fiction", "magical", "history"],
        "reactions": 4,
    },
    {
        "id": 11,
        "title": "It wasn't quite yet time to panic.",
        "body": "It wasn't quite yet time to panic. There was still time to salvage the situation. At least that is what she was telling himself. The reality was that it was time to panic and there wasn't time to salvage the situation, but he continued to delude himself into believing there was.",
        "userId": 25,
        "tags": ["mystery", "american", "history"],
        "reactions": 5,
    },
    {
        "id": 12,
        "title": "She was aware that things could go wrong.",
        "body": "She was aware that things could go wrong. In fact, she had trained her entire life in anticipation that things would go wrong one day. She had quiet confidence as she started to see that this was the day that all her training would be worthwhile and useful. At this point, she had no idea just how wrong everything would go that day.",
        "userId": 26,
        "tags": ["love", "english"],
        "reactions": 7,
    },
]

# newPost = []
# for data in posts:
#     temp = {
#         "myId" : data["id"],
#         "titleName" : data["title"],
#         "structer" : data["body"],
#         "tag" : data["tags"],
#         "reaction" : data["reactions"]

#     }
#     newPost.append(temp)
# print(newPost)
# for item in newPost:
#     print(item)


todos = [
    {
        "id": 1,
        "todo": "Do something nice for someone I care about",
        "completed": True,
        "userId": 26,
    },
    {
        "id": 2,
        "todo": "Memorize the fifty states and their capitals",
        "completed": False,
        "userId": 48,
    },
    {"id": 3, "todo": "Watch a classic movie", "completed": False, "userId": 4},
    {
        "id": 4,
        "todo": "Contribute code or a monetary donation to an open-source software project",
        "completed": False,
        "userId": 48,
    },
    {"id": 5, "todo": "Solve a Rubik's cube", "completed": False, "userId": 31},
    {
        "id": 6,
        "todo": "Bake pastries for me and neighbor",
        "completed": False,
        "userId": 39,
    },
    {"id": 7, "todo": "Go see a Broadway production", "completed": False, "userId": 32},
    {
        "id": 8,
        "todo": "Write a thank you letter to an influential person in my life",
        "completed": True,
        "userId": 13,
    },
    {
        "id": 9,
        "todo": "Invite some friends over for a game night",
        "completed": False,
        "userId": 47,
    },
    {
        "id": 10,
        "todo": "Have a football scrimmage with some friends",
        "completed": False,
        "userId": 19,
    },
    {
        "id": 11,
        "todo": "Text a friend I haven't talked to in a long time",
        "completed": False,
        "userId": 39,
    },
    {"id": 12, "todo": "Organize pantry", "completed": True, "userId": 39},
    {"id": 13, "todo": "Buy a new house decoration", "completed": False, "userId": 16},
    {
        "id": 14,
        "todo": "Plan a vacation I've always wanted to take",
        "completed": False,
        "userId": 28,
    },
    {"id": 15, "todo": "Clean out car", "completed": False, "userId": 33},
    {"id": 16, "todo": "Draw and color a Mandala", "completed": True, "userId": 24},
    {
        "id": 17,
        "todo": "Create a cookbook with favorite recipes",
        "completed": False,
        "userId": 1,
    },
    {"id": 18, "todo": "Bake a pie with some friends", "completed": False, "userId": 1},
    {"id": 19, "todo": "Create a compost pile", "completed": True, "userId": 5},
    {"id": 20, "todo": "Take a hike at a local park", "completed": True, "userId": 43},
    {
        "id": 21,
        "todo": "Take a class at local community center that interests you",
        "completed": False,
        "userId": 22,
    },
    {
        "id": 22,
        "todo": "Research a topic interested in",
        "completed": False,
        "userId": 4,
    },
    {
        "id": 23,
        "todo": "Plan a trip to another country",
        "completed": True,
        "userId": 37,
    },
    {"id": 24, "todo": "Improve touch typing", "completed": False, "userId": 45},
    {"id": 25, "todo": "Learn Express.js", "completed": False, "userId": 49},
    {"id": 26, "todo": "Learn calligraphy", "completed": False, "userId": 50},
    {
        "id": 27,
        "todo": "Have a photo session with some friends",
        "completed": False,
        "userId": 14,
    },
    {"id": 28, "todo": "Go to the gym", "completed": False, "userId": 15},
    {"id": 29, "todo": "Make own LEGO creation", "completed": False, "userId": 30},
    {"id": 30, "todo": "Take cat on a walk", "completed": False, "userId": 15},
]

# for data in todos:
#     temp = {
#         "myId" : data["id"],
#         "to do" : data["todo"],
#         "finish" : data["completed"],
#         "id" : data["userId"],  
#         }
#     newData.append(temp)
# for item in newData:
#     print(item)
    